package installer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// StatuslineSnippet is the managed block injected into the user's
// statusline-command.sh. It runs token-monitor only if the binary is on PATH
// and silently no-ops otherwise — keeping the user's status line working even
// when token-monitor is uninstalled or unavailable.
const StatuslineSnippet = MarkerStart + `
if command -v token-monitor >/dev/null 2>&1; then
  tm_extra=$(echo "$input" | token-monitor status --from-stdin --breakdown --compact 2>/dev/null)
  [ -n "$tm_extra" ] && printf " \033[2m|\033[0m \033[0;35m%s\033[0m" "$tm_extra"
fi
` + MarkerEnd

// StatuslineStub is created when no statusline script exists yet. It reads
// Claude Code's JSON input from stdin into $input so the managed block can
// pipe it on.
const StatuslineStub = `#!/bin/bash
# Auto-generated by 'token-monitor install statusline'.
# Read this script's input (Claude Code passes JSON on stdin):
input=$(cat)
`

// DefaultStatuslinePath returns ~/.claude/statusline-command.sh, the location
// Claude Code reads when wired via settings.json's statusLine.command.
func DefaultStatuslinePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("locate home directory: %w", err)
	}
	return filepath.Join(home, ".claude", "statusline-command.sh"), nil
}

// InstallStatusline patches (or creates) the script at path with the managed
// block.
//
// Behaviour:
//   - If the file is missing, a stub is created (unless dryRun) before
//     injecting the block.
//   - Real installs always backup the existing file (if any) before writing.
//   - Idempotent: running twice produces identical bytes (use HasMarkerBlock
//     to short-circuit "already installed" reporting).
//   - Uninstall removes the managed block. If, after removal, the remaining
//     content equals the auto-generated stub (or is empty), the file is
//     deleted so a fresh install starts clean.
//
// The returned summary is human-readable and intended for the CLI to print.
func InstallStatusline(path string, dryRun, uninstall bool) (string, error) {
	if path == "" {
		var err error
		path, err = DefaultStatuslinePath()
		if err != nil {
			return "", err
		}
	}

	existing, fileExisted, err := readFileIfExists(path)
	if err != nil {
		return "", err
	}

	if uninstall {
		return uninstallStatusline(path, existing, fileExisted, dryRun)
	}

	// Install path.
	base := existing
	createdStub := false
	if !fileExisted {
		base = StatuslineStub
		createdStub = true
	}

	updated := PatchMarkerBlock(base, StatuslineSnippet)

	if updated == existing && fileExisted {
		return fmt.Sprintf("statusline: already installed at %s (no changes)", path), nil
	}

	if dryRun {
		return formatDryRun("statusline", path, existing, updated, createdStub), nil
	}

	if dirErr := ensureParentDir(path); dirErr != nil {
		return "", dirErr
	}

	backupPath := ""
	if fileExisted {
		backupPath, err = BackupFile(path)
		if err != nil {
			return "", err
		}
	}

	if writeErr := writeFileExecutable(path, updated); writeErr != nil {
		return "", writeErr
	}

	summary := fmt.Sprintf("statusline: installed at %s", path)
	if createdStub {
		summary = fmt.Sprintf("statusline: created stub and installed at %s", path)
	}
	if backupPath != "" {
		summary += fmt.Sprintf(" (backup: %s)", backupPath)
	}
	return summary, nil
}

func uninstallStatusline(path, existing string, fileExisted, dryRun bool) (string, error) {
	if !fileExisted {
		return fmt.Sprintf("statusline: nothing to uninstall (no file at %s)", path), nil
	}
	if !HasMarkerBlock(existing) {
		return fmt.Sprintf("statusline: nothing to uninstall (no managed block in %s)", path), nil
	}

	updated := PatchMarkerBlock(existing, "")

	// If only the stub remains (or nothing), drop the file entirely so a fresh
	// install starts from a clean slate.
	residualEmpty := strings.TrimSpace(updated) == ""
	residualStubOnly := strings.TrimSpace(updated) == strings.TrimSpace(StatuslineStub)
	deleteFile := residualEmpty || residualStubOnly

	if dryRun {
		action := "would patch"
		if deleteFile {
			action = "would delete"
		}
		return fmt.Sprintf("statusline (dry-run): %s %s\n--- before ---\n%s\n--- after ---\n%s",
			action, path, existing, updated), nil
	}

	backupPath, err := BackupFile(path)
	if err != nil {
		return "", err
	}

	if deleteFile {
		if removeErr := os.Remove(path); removeErr != nil {
			return "", fmt.Errorf("remove %s: %w", path, removeErr)
		}
		return fmt.Sprintf("statusline: removed managed block and deleted %s (backup: %s)", path, backupPath), nil
	}

	if writeErr := writeFileExecutable(path, updated); writeErr != nil {
		return "", writeErr
	}
	return fmt.Sprintf("statusline: removed managed block from %s (backup: %s)", path, backupPath), nil
}

// readFileIfExists returns (content, existed, err). A missing file produces
// ("", false, nil); other I/O failures bubble up.
func readFileIfExists(path string) (string, bool, error) {
	data, err := os.ReadFile(path) //nolint:gosec // path supplied by caller (CLI flag or well-known)
	if err != nil {
		if os.IsNotExist(err) {
			return "", false, nil
		}
		return "", false, fmt.Errorf("read %s: %w", path, err)
	}
	return string(data), true, nil
}

func ensureParentDir(path string) error {
	dir := filepath.Dir(path)
	if dir == "" || dir == "." {
		return nil
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}
	return nil
}

func writeFileExecutable(path, content string) error {
	if err := atomicWriteFile(path, []byte(content), 0o755); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func formatDryRun(label, path, before, after string, createdStub bool) string {
	prefix := fmt.Sprintf("%s (dry-run): would write %s", label, path)
	if createdStub {
		prefix += " (creating new stub)"
	}
	beforeRendered := before
	if createdStub {
		beforeRendered = "(file does not exist; will be created)"
	}
	return fmt.Sprintf("%s\n--- before ---\n%s\n--- after ---\n%s", prefix, beforeRendered, after)
}
